# Configuration related to default returns

- name: NOSVILLE_SPAWN
  map_id: 1
  map_x: 80
  map_y: 116
  radius: 5
- name: KREM_SPAWN
  map_id: 20
  map_x: 9
  map_y: 92
  radius: 3
- name: ALVEUS_SPAWN
  map_id: 145
  map_x: 13
  map_y: 110
  radius: 9
- name: ACT4_DEMON_SPAWN
  map_id: 131
  map_x: 40
  map_y: 43
  radius: 3
- name: ACT4_ANGEL_SPAWN
  map_id: 130
  map_x: 40
  map_y: 43
  radius: 3
- name: MORTAZ_DESERT_PORT
  map_id: 170
  map_x: 87
  map_y: 52
  radius: 3
- name: AKAMUR_CAMP
  map_id: 177
  map_x: 148
  map_y: 70
  radius: 3
- name: DESERT_EAGLE_CITY
  map_id: 189
  map_x: 54
  map_y: 168
  radius: 3