# Configuration related to Time-Spaces placment, rewards, types

- ts_id: 0
  min_level: 1
  max_level: 99
  name: TS_0_NAME
  description: TS_0_DESCRIPTION
  seeds_of_power_required: 0
  is_hero: false
  is_special: false
  is_hidden: false
  min_players: 1
  max_players: 3
  rewards:
    draw: # always one, max 5
    - item_vnum: 2023
      amount: 1
    - item_vnum: 2024
      amount: 1
    - item_vnum: 2025
      amount: 1
    - item_vnum: 2026
      amount: 1
    - item_vnum: 2027
      amount: 1
    special: # once, max 2
    - item_vnum: 2016
      amount: 2
    bonus: # always, max 3
    - item_vnum: 13
      amount: 1
  placement:
  - map_id: 1
    map_x: 134
    map_y: 36
#
- ts_id: 9
  min_level: 18
  max_level: 99
  name: TS_9_NAME
  description: TS_9_DESCRIPTION
  seeds_of_power_required: 1
  is_hero: true
  is_special: false
  is_hidden: false
  min_players: 1
  max_players: 3
  rewards:
    draw: # always one, max 5
    - item_vnum: 162
      amount: 1
    - item_vnum: 168
      amount: 1
    - item_vnum: 174
      amount: 1
    special: # once, max 2
    - item_vnum: 1016
      amount: 1
    bonus: # always, max 3
    - item_vnum: 721
      amount: 1
  placement:
  - map_id: 6
    map_x: 9
    map_y: 81
#
- ts_id: 14
  min_level: 24
  max_level: 99
  name: TS_14_NAME
  description: TS_14_DESCRIPTION
  seeds_of_power_required: 2
  is_hero: false
  is_special: false
  is_hidden: false
  min_players: 1
  max_players: 3
  rewards:
    draw: # always one, max 5
    - item_vnum: 717
      amount: 1
    - item_vnum: 709
      amount: 1
    special: # once, max 2
    - item_vnum: 1013
      amount: 30
    bonus: # always, max 3
    - item_vnum: 2028
      amount: 5
    - item_vnum: 1087
      amount: 1
  placement:
  - map_id: 7
    map_x: 75
    map_y: 81
#
- ts_id: 15
  min_level: 25
  max_level: 99
  name: TS_15_NAME
  description: TS_15_DESCRIPTION
  seeds_of_power_required: 2
  is_hero: true
  is_special: false
  is_hidden: false
  min_players: 1
  max_players: 3
  rewards:
    draw: # always one, max 5
    - item_vnum: 20
      amount: 1
    - item_vnum: 34
      amount: 1
    - item_vnum: 48
      amount: 1
    special: # once, max 2
    - item_vnum: 800
      amount: 1
    bonus: # always, max 3
    - item_vnum: 1013
      amount: 5
    - item_vnum: 1087
      amount: 1
  placement:
  - map_id: 7
    map_x: 130
    map_y: 134
#
- ts_id: 16
  min_level: 26
  max_level: 99
  name: TS_16_NAME
  description: TS_16_DESCRIPTION
  seeds_of_power_required: 2
  is_hero: false
  is_special: false
  is_hidden: false
  min_players: 1
  max_players: 3
  rewards:
    draw: # always one, max 5
    - item_vnum: 70
      amount: 1
    - item_vnum: 80
      amount: 1
    - item_vnum: 88
      amount: 1
    special: # once, max 2
    - item_vnum: 1010
      amount: 50
    bonus: # always, max 3
    - item_vnum: 2132
      amount: 1
    - item_vnum: 1087
      amount: 1
  placement:
  - map_id: 4
    map_x: 35
    map_y: 142
#
- ts_id: 17
  min_level: 27
  max_level: 99
  name: TS_17_NAME
  description: TS_17_DESCRIPTION
  seeds_of_power_required: 2
  is_hero: false
  is_special: false
  is_hidden: false
  min_players: 1
  max_players: 3
  rewards:
    draw: # always one, max 5
    - item_vnum: 163
      amount: 1
    - item_vnum: 169
      amount: 1
    - item_vnum: 175
      amount: 1
    special: # once, max 2
    - item_vnum: 2101
      amount: 40
    bonus: # always, max 3
    - item_vnum: 2099
      amount: 2
    - item_vnum: 1087
      amount: 1
  placement:
  - map_id: 4
    map_x: 145
    map_y: 146
#
- ts_id: 19
  min_level: 29
  max_level: 99
  name: TS_19_NAME
  description: TS_19_DESCRIPTION
  seeds_of_power_required: 2
  is_hero: false
  is_special: false
  is_hidden: false
  min_players: 1
  max_players: 3
  rewards:
    draw: # always one, max 5
    - item_vnum: 136
      amount: 1
    - item_vnum: 143
      amount: 1
    - item_vnum: 150
      amount: 1
    special: # once, max 2
    - item_vnum: 2129
      amount: 10
    bonus: # always, max 3
    - item_vnum: 2129
      amount: 2
    - item_vnum: 1087
      amount: 1
  placement:
  - map_id: 4
    map_x: 189
    map_y: 65
#
- ts_id: 20
  min_level: 30
  max_level: 99
  name: TS_20_NAME
  description: TS_20_DESCRIPTION
  seeds_of_power_required: 3
  is_hero: false
  is_special: false
  is_hidden: false
  min_players: 1
  max_players: 3
  rewards:
    draw: # always one, max 5
    - item_vnum: 3700
      amount: 1
    - item_vnum: 235
      amount: 1
    special: # once, max 2
    - item_vnum: 1015
      amount: 2
    bonus: # always, max 3
    - item_vnum: 2135
      amount: 1
    - item_vnum: 2136
      amount: 1
    - item_vnum: 1087
      amount: 1
  placement:
  - map_id: 4
    map_x: 136
    map_y: 77
#
- ts_id: 21
  min_level: 31
  max_level: 99
  name: TS_21_NAME
  description: TS_21_DESCRIPTION
  seeds_of_power_required: 3
  is_hero: false
  is_special: false
  is_hidden: false
  min_players: 1
  max_players: 3
  rewards:
    draw: # always one, max 5
    - item_vnum: 98
      amount: 1
    - item_vnum: 111
      amount: 1
    - item_vnum: 124
      amount: 1
    special: # once, max 2
    - item_vnum: 224
      amount: 1
    bonus: # always, max 3
    - item_vnum: 2131
      amount: 1
    - item_vnum: 1087
      amount: 1
  placement:
  - map_id: 4
    map_x: 121
    map_y: 26
#
- ts_id: 22
  min_level: 32
  max_level: 99
  name: TS_22_NAME
  description: TS_22_DESCRIPTION
  seeds_of_power_required: 3
  is_hero: false
  is_special: false
  is_hidden: false
  min_players: 1
  max_players: 3
  rewards:
    draw: # always one, max 5
    - item_vnum: 180
      amount: 1
    - item_vnum: 181
      amount: 1
    - item_vnum: 182
      amount: 1
    special: # once, max 2
    - item_vnum: 801
      amount: 1
    bonus: # always, max 3
    - item_vnum: 1087
      amount: 1
  placement:
  - map_id: 4
    map_x: 44
    map_y: 48
#
- ts_id: 25
  min_level: 35
  max_level: 99
  name: TS_25_NAME
  description: TS_25_DESCRIPTION
  seeds_of_power_required: 3
  is_hero: false
  is_special: false
  is_hidden: false
  min_players: 1
  max_players: 3
  rewards:
    draw: # always one, max 5
    - item_vnum: 517
      amount: 1
    - item_vnum: 518
      amount: 1
    special: # once, max 2
    - item_vnum: 2043
      amount: 15
    - item_vnum: 1019
      amount: 15
    bonus: # always, max 3
    - item_vnum: 2135
      amount: 1
    - item_vnum: 2136
      amount: 1
    - item_vnum: 1087
      amount: 1
  placement:
  - map_id: 5
    map_x: 151
    map_y: 167
#
- ts_id: 31
  min_level: 41
  max_level: 99
  name: TS_31_NAME
  description: TS_31_DESCRIPTION
  seeds_of_power_required: 4
  is_hero: false
  is_special: false
  is_hidden: false
  min_players: 1
  max_players: 3
  rewards:
    draw: # always one, max 5
    - item_vnum: 712
      amount: 1
    - item_vnum: 1028
      amount: 4
    special: # once, max 2
    - item_vnum: 802
      amount: 1
    bonus: # always, max 3
    - item_vnum: 2134
      amount: 1
    - item_vnum: 1087
      amount: 1
  placement:
  - map_id: 10
    map_x: 60
    map_y: 92
#
- ts_id: 33
  min_level: 43
  max_level: 99
  name: TS_33_NAME
  description: TS_33_DESCRIPTION
  seeds_of_power_required: 4
  is_hero: true
  is_special: false
  is_hidden: false
  min_players: 1
  max_players: 3
  rewards:
    draw: # always one, max 5
    - item_vnum: 138
      amount: 1
    - item_vnum: 145
      amount: 1
    - item_vnum: 152
      amount: 1
    special: # once, max 2
    - item_vnum: 220
      amount: 1
    bonus: # always, max 3
    - item_vnum: 1027
      amount: 2
    - item_vnum: 1087
      amount: 1
  placement:
  - map_id: 10
    map_x: 98
    map_y: 2
#
- ts_id: 35
  min_level: 45
  max_level: 99
  name: TS_35_NAME
  description: TS_35_DESCRIPTION
  seeds_of_power_required: 4
  is_hero: false
  is_special: false
  is_hidden: false
  min_players: 1
  max_players: 3
  rewards:
    draw: # always one, max 5
    - item_vnum: 102
      amount: 1
    - item_vnum: 115
      amount: 1
    - item_vnum: 128
      amount: 1
    special: # once, max 2
    - item_vnum: 803
      amount: 1
    bonus: # always, max 3
    - item_vnum: 1087
      amount: 1
  placement:
  - map_id: 11
    map_x: 108
    map_y: 7
#
- ts_id: 36
  min_level: 46
  max_level: 99
  name: TS_36_NAME
  description: TS_36_DESCRIPTION
  seeds_of_power_required: 4
  is_hero: false
  is_special: false
  is_hidden: false
  min_players: 1
  max_players: 3
  rewards:
    draw: # always one, max 5
    - item_vnum: 525
      amount: 1
    - item_vnum: 526
      amount: 1
    special: # once, max 2
    - item_vnum: 1020
      amount: 15
    bonus: # always, max 3
    - item_vnum: 1087
      amount: 1
  placement:
  - map_id: 11
    map_x: 109
    map_y: 114
#
- ts_id: 38
  min_level: 48
  max_level: 99
  name: TS_38_NAME
  description: TS_38_DESCRIPTION
  seeds_of_power_required: 4
  is_hero: false
  is_special: false
  is_hidden: false
  min_players: 1
  max_players: 3
  rewards:
    draw: # always one, max 5
    - item_vnum: 1011
      amount: 2
    - item_vnum: 1011
      amount: 4
    - item_vnum: 1011
      amount: 6
    - item_vnum: 1011
      amount: 8
    - item_vnum: 1011
      amount: 10
    special: # once, max 2
    - item_vnum: 2036
      amount: 15
    - item_vnum: 2040
      amount: 15
    bonus: # always, max 3
    - item_vnum: 2127
      amount: 1
    - item_vnum: 1087
      amount: 1
  placement:
  - map_id: 12
    map_x: 9
    map_y: 13
#
- ts_id: 39
  min_level: 49
  max_level: 99
  name: TS_39_NAME
  description: TS_39_DESCRIPTION
  seeds_of_power_required: 4
  is_hero: true
  is_special: false
  is_hidden: false
  min_players: 1
  max_players: 3
  rewards:
    draw: # always one, max 5
    - item_vnum: 1
      amount: 1
    special: # once, max 2
    - item_vnum: 2127
      amount: 99
    bonus: # always, max 3
    - item_vnum: 2127
      amount: 10
    - item_vnum: 1087
      amount: 1
  placement:
  - map_id: 80
    map_x: 19
    map_y: 87
#
- ts_id: 45
  min_level: 55
  max_level: 99
  name: TS_45_NAME
  description: TS_45_DESCRIPTION
  seeds_of_power_required: 5
  is_hero: true
  is_special: false
  is_hidden: false
  min_players: 1
  max_players: 3
  rewards:
    draw: # always one, max 5
    - item_vnum: 3701
      amount: 1
    - item_vnum: 3702
      amount: 1
    - item_vnum: 3703
      amount: 1
    - item_vnum: 3704
      amount: 1
    special: # once, max 2
    - item_vnum: 221
      amount: 1
    bonus: # always, max 3
    - item_vnum: 2135
      amount: 5
    - item_vnum: 2136
      amount: 5
    - item_vnum: 1087
      amount: 1
  placement:
  - map_id: 17
    map_x: 41
    map_y: 24