# Configuration related to normal equipment upgrade rates

- upgrade: 0
  up_fix: 0
  up_fail: 0
  gold: 500
  cella: 20
  gem: 1
- upgrade: 1
  up_fix: 0
  up_fail: 0
  gold: 1500
  cella: 50
  gem: 1
- upgrade: 2
  up_fix: 100
  up_fail: 0
  gold: 3000
  cella: 80
  gem: 2
- upgrade: 3
  up_fix: 150
  up_fail: 50
  gold: 10000
  cella: 120
  gem: 2
- upgrade: 4
  up_fix: 200
  up_fail: 200
  gold: 30000
  cella: 160
  gem: 3
- upgrade: 5
  up_fix: 200
  up_fail: 400
  gold: 80000
  cella: 220
  gem: 1
- upgrade: 6
  up_fix: 200
  up_fail: 600
  gold: 150000
  cella: 280
  gem: 1
- upgrade: 7
  up_fix: 150
  up_fail: 800
  gold: 400000
  cella: 380
  gem: 2
- upgrade: 8
  up_fix: 100
  up_fail: 890
  gold: 700000
  cella: 480
  gem: 2
- upgrade: 9
  up_fix: 50
  up_fail: 945
  gold: 1000000
  cella: 600
  gem: 3
