# Configuration related to hero equipment upgrade rates

- upgrade: 0
  up_fix: 0
  up_fail: 50
  gold: 5000
  cella: 40
  gem: 2
- upgrade: 1
  up_fix: 0
  up_fail: 50
  gold: 15000
  cella: 100
  gem: 2
- upgrade: 2
  up_fix: 10
  up_fail: 45
  gold: 30000
  cella: 160
  gem: 4
- upgrade: 3
  up_fix: 15
  up_fail: 45
  gold: 100000
  cella: 240
  gem: 4
- upgrade: 4
  up_fix: 20
  up_fail: 50
  gold: 300000
  cella: 320
  gem: 6
- upgrade: 5
  up_fix: 20
  up_fail: 60
  gold: 800000
  cella: 440
  gem: 2
- upgrade: 6
  up_fix: 10
  up_fail: 70
  gold: 1500000
  cella: 560
  gem: 2
- upgrade: 7
  up_fix: 5
  up_fail: 85
  gold: 4000000
  cella: 760
  gem: 4
- upgrade: 8
  up_fix: 3
  up_fail: 92
  gold: 7000000
  cella: 960
  gem: 4
- upgrade: 9
  up_fix: 1
  up_fail: 98
  gold: 10000000
  cella: 1200
  gem: 6
