Document: vanosilla
Title: Debian vanosilla Manual
Author: Wallcroft
Abstract: This manual describes what vanosilla is
 and how it can be used to
 manage online manuals on Debian systems.
Section: utils

Format: debiandoc-sgml
Files: /usr/share/doc/vanosilla/vanosilla.sgml.gz

Format: postscript
Files: /usr/share/doc/vanosilla/vanosilla.ps.gz

Format: text
Files: /usr/share/doc/vanosilla/vanosilla.text.gz

Format: HTML
Index: /usr/share/doc/vanosilla/html/index.html
Files: /usr/share/doc/vanosilla/html/*.html
