# Configuration related to Act4 - points generation, Mukraju spawn

maximum_faction_points: 60000
pve_faction_points: true
faction_points_per_pve_kill: 15
pvp_faction_points: true
faction_points_per_pvp_kill: 300
banned_map_ids_to_angels:
- 131
banned_map_ids_to_demons:
- 130
point_generation:
- player_amount:
    minimum: 0
    maximum: 4
  points_amount: 300    # 100
- player_amount:
    minimum: 5
    maximum: 9
  points_amount: 700    # 500
- player_amount:
    minimum: 10
    maximum: 19
  points_amount: 850    # 650
- player_amount:
    minimum: 20
    maximum: 39
  points_amount: 1000   # 800
- player_amount:
    minimum: 40
    maximum: 59
  points_amount: 1250
- player_amount:
    minimum: 60
    maximum: 79
  points_amount: 2250
- player_amount:
    minimum: 80
    maximum: 99
  points_amount: 3500
- player_amount:
    minimum: 100
    maximum: null   # any more players
  points_amount: 4500   # 100+ players
reset_date: 05:00:00    # daily reset at 5 am
mukraju_end_span: 00:05:00
mukraju_radius: 10  # if he walks 10 cells away from his spawn, he will be teleported there
angel_mukraju_spawn:
  monster_vnum: 556
  map_id: 132
  map_x: 114
  map_y: 92
demon_mukraju_spawn:
  monster_vnum: 556
  map_id: 133
  map_x: 20
  map_y: 95
