# Configuration related to Buffs - custom min. and max. duration

- buff_vnum: 85
  is_permanent: false
  min_duration: 15000
  max_duration: 30000
- buff_vnum: 115
  is_permanent: false
  min_duration: 3600000
  max_duration: 3600000
- buff_vnum: 319
  is_permanent: true
  min_duration: -1
  max_duration: -1
- buff_vnum: 339
  is_permanent: true
  min_duration: -1
  max_duration: -1
- buff_vnum: 340
  is_permanent: true
  min_duration: -1
  max_duration: -1
- buff_vnum: 360
  is_permanent: false
  min_duration: 3600000
  max_duration: 3600000
- buff_vnum: 361
  is_permanent: false
  min_duration: 3600000
  max_duration: 3600000
- buff_vnum: 362
  is_permanent: false
  min_duration: 3600000
  max_duration: 3600000
- buff_vnum: 471
  is_permanent: true
  min_duration: -1
  max_duration: -1
- buff_vnum: 472
  is_permanent: true
  min_duration: -1
  max_duration: -1
- buff_vnum: 559
  is_permanent: false
  min_duration: 15000
  max_duration: 40000
- buff_vnum: 634
  is_permanent: true
  min_duration: -1
  max_duration: -1
- buff_vnum: 635
  is_permanent: true
  min_duration: -1
  max_duration: -1
- buff_vnum: 2154
  is_permanent: false
  min_duration: 2000
  max_duration: 9000
- buff_vnum: 2155
  is_permanent: false
  min_duration: 2500
  max_duration: 9500
- buff_vnum: 2156
  is_permanent: false
  min_duration: 3000
  max_duration: 10000
- buff_vnum: 2157
  is_permanent: false
  min_duration: 3500
  max_duration: 10500
- buff_vnum: 2158
  is_permanent: false
  min_duration: 4000
  max_duration: 11000
- buff_vnum: 2159
  is_permanent: false
  min_duration: 4500
  max_duration: 11500
- buff_vnum: 2160
  is_permanent: false
  min_duration: 8000
  max_duration: 16000
- buff_vnum: 20531
  is_permanent: true
  min_duration: -1
  max_duration: -1
- buff_vnum: 20552
  is_permanent: true
  min_duration: -1
  max_duration: -1
