name: Create the DEB

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  Create_Packages:
    name: Create Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: "REPO"

      - name: Copy necessary files to build the package
        run: |
          mkdir -p PKG_SOURCE/DEBIAN
          cp -Rf REPO/debian/* PKG_SOURCE/DEBIAN
          cp -Rf REPO/src/* PKG_SOURCE/
          dpkg-deb --build PKG_SOURCE vanosilla.deb

      - name: Release the Package
        uses: softprops/action-gh-release@v1
        with:
          files: vanosilla.deb
